name: PR!

on:
  pull_request:

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: second branch name  
        run: echo "branch=$GITHUB_HEAD_REF" >> $GITHUB_ENV
      - name: chaneckout main
        run: git checkout "main"
      - name: test1
        run: |
          lastFile=$(ls -t1 db/migrate/*.rb | head -n 1 | awk -F '[/]' '{print $3}' | awk -F '[_]' '{print $1}')
          echo $lastFile
      - name: checkout PR branch 
        run: git checkout 'main'
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for eachfile in ${{ steps.files.outputs.added }}
          do 
            if [[ "$eachfile" =~ db/migrate* ]]; then
              file=$(echo $eachfile | awk -F '[/]' '{print $3}' | awk -F '[_]' '{print $1}')
              echo $file File added
                if (( $file < $lastFile )); then
                  echo $eachfile could not be less or equall then $lastFile
                  exit 1
                fi
             fi   
          done
          echo ${{ steps.files.outputs.added }}
