name: PR!

on:
  push:
    branches:
      - main

jobs:
  check_latest_file:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        run: |
          lastFile=$(ls -t1 dir | head -n 1 | awk -F '[_]' '{print $1}')
          echo $lastFile
      - uses: actions/checkout@v2
        with:
        path: main
        run: |
          lastFile=$(ls -t1 dir | head -n 1 | awk -F '[_]' '{print $1}')
          echo $lastFile
          