name: PR!

on:
  pull_request:

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: chaneckout main
        run: git checkout "main"
      - name: test1
        run: |
          lastFile=$(find db/migrate/*.rb -mtime -15 | tail -1 | awk -F '[/]' '{print $3}' | awk -F '[_]' '{print $1}')
          echo "lastFile=$lastFile" >> $GITHUB_ENV
      - uses: jitterbit/get-changed-files@v1
        id: files        
        continue-on-error: true
      - run: |
          echo ${{ env.lastFile }}
          for eachfile in ${{ steps.files.outputs.added }}
          do 
            if [[ "$eachfile" =~ db/migrate* ]]; then
              file=$(echo $eachfile | awk -F '[/]' '{print $3}' | awk -F '[_]' '{print $1}')
              echo $file File added
                if (( $file < ${{ env.lastFile }} )); then
                  echo $eachfile could not be less or equall then $lastFile
                  exit 1
                fi
             fi   
          done
          echo ${{ steps.files.outputs.added }}
