name: PR!

on:
  push:
    branches:
      - main


jobs:
  check_latest_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: ls -t1 dir |  head -n 1