name: PR!

on:
  pull_request:

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: second branch name  
        run: echo "branch=$GITHUB_HEAD_REF" >> $GITHUB_ENV
      - name: chaneckout main
        run: git checkout "$DEFAULT_BRANCH"
      - name: test1
        run: |
          lastFile=$(ls -t1 dir | head -n 1 | awk -F '[_]' '{print $1}')
          echo $lastFile
          echo "lastFile=$lastFile" >> $GITHUB_ENV
      - name: checkout PR branch 
        run: git checkout ${{ env.branch }}
      - name: test2
        run: |
          yourfilenames=$(ls dir)
          brokeFiles=()
          for eachfile in $yourfilenames
          do
            file=$(echo $eachfile | awk -F '[_]' '{print $1}')
              if (( ${{ env.lastFile }} < $file )); then
                echo $eachfile could not be less then $lastFile
                exit 1
              fi
          done