name: PR!

on:
  push:
    branches:
      - main

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: second branch name  
        run: echo "branch=$GITHUB_HEAD_REF" >> $GITHUB_ENV
      - name: chaneckout main
        run: git checkout main
      - name: test1
        run: |
          lastFile=$(ls -t1 dir | head -n 1 | awk -F '[_]' '{print $1}')
          echo $lastFile
          echo "lastFile=$lastFile" >> $GITHUB_ENV
      - name: checkout PR branch 
        run: ${{ env.branch }}
      - name: test2
        run: |
          yourfilenames=$(ls dir)
          brokeFiles=()
          for eachfile in $yourfilenames
          do
            file=$(echo $eachfile | awk -F '[_]' '{print $1}')
              if (( ${{ env.lastFile }} < $file )); then
                brokeFiles+=($eachfile)
                echo 1
              fi
          done
          echo "brokeFiles=$brokeFiles" >> $GITHUB_ENV
          echo $brokeFiles
  