name: PR!

on:
  push:
    branches:
      - main

jobs:
  check_latest_file:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      name: 'use main'
      with:
        ref: main

      - name: 'test1'
        run: echo 'test1'

      - name: 'test2'
        run: echo 'test2'