name: PR!

on:
  push:
    branches:
      - main

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test1
        run: |
          lastFile=$(ls -t1 dir | head -n 1 | awk -F '[_]' '{print $1}')
          echo $lastFile  
      - name: test2
        run: |
          ls -t1 dir