name: PR!

on:
  push:
    branches:
      - main

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test1
        run: |
          lastFile=$(ls -t1 dir | head -n 1 | awk -F '[_]' '{print $1}')
          echo $lastFile
          echo "action_state=$lastFile" >> $GITHUB_ENV
      - name: test2
        run: |
          yourfilenames=$(ls dir)
          echo $yourfilenames
          echo "${{ env.action_state }}" 
          for eachfile in $yourfilenames
          do
            file=$(echo $eachfile | awk -F '[_]' '{print $1}')
              if (( ${{ env.action_state }} < $file )); then
                echo 1
              fi
          done
          echo 0