name: PR!

on:
  pull_request:

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: second branch name  
        run: echo "branch=$GITHUB_HEAD_REF" >> $GITHUB_ENV
      - name: chaneckout main
        run: git checkout "main"
      - name: test1
        run: |
          lastFile=$(ls -t1 dir | head -n 1 | awk -F '[_]' '{print $1}')
          echo $lastFile
          echo "lastFile=$lastFile" >> $GITHUB_ENV
      - name: test git ref if changed
        run: |
          echo $GITHUB_HEAD_REF
      - name: checkout PR branch 
        run: git checkout $GITHUB_HEAD_REF
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo ${{ steps.files.outputs.all }}
