name: PR!

on:
  push:
    branches:
      - main

jobs:
  check_latest_file:
    runs-on: ubuntu-latest
    steps:
      - name: ls
        - uses: actions/checkout@v2
          run: |
            ls -l