name: PR!

on:
  push:
    branches:
      - main
    paths:
      - 'dir/*.rb'

jobs:
  check_latest_file:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          ls / -t1 |  head -n 1